### ISSUE TITLE
Gtk3 dialog sidebar icon padding

### ISSUE THREAD

**Issue by bookletchoir** [Antergos/Numix-Frost#15]
With the recently update (v3.0.1-3) from antergos repository, the sidebar and address bar icons of Gtk3 dialog seems to be stuck with text label.

![numix-frost-theme](http://i.imgur.com/jmy8IdX.png)

With default theme (adwaita) and older version of numix-frost, I don't have that problem.

Can you do something with it?

**Comment by bookletchoir** [comment]
Adding these lines to `~/.config/gtk-3.0/gtk.css` does the trick, but the icon in address bar still stuck to text label.
```css
.sidebar-icon {
    padding-left: 10px;
    padding-right: 10px;
}
```
