### ISSUE TITLE
Nemo right click context menu padding

### ISSUE THREAD

**Issue by bendovercz** [Antergos/Numix-Frost#16]
Since version 3.0.0 there appears to be some kind of padding in Nemo context menu that prevents closing it (this context menu) with clicking above and on the left side of the context menu.

And also (but this has been there for a previous version too) when scrolling a lots of files/dirs and you reach the top/bottom then 'animation' happens. Thats okay but when this animation happens and you hit back (on your mouse/backspace) the animation gets stuck and is visible all the time - http://i.imgur.com/PFMFZlz.png

**Comment by bookletchoir** [comment]
For the context menu border, you can add this to `~/.config/gtk-3.0/gtk.css`

```css
.window-frame.csd.popup {
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.13);
}
```
